=== Ahmed-Refaat/yamcs/yamcs-web/src/main/uss/symlib/Libraries.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="library">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="comment" type="xs:string"/>
				<xs:element ref="symbol" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="symbol">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string"/>
				<xs:element name="comment" type="xs:string"/>
				<xs:element ref="image" maxOccurs="unbounded"/>				
				<xs:element name="type" type="Choice"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="image">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="URL">
					<xs:attribute name="default">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="false"/>
								<xs:enumeration value="true"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="state" type="xs:string"/>
					<xs:attribute name="library" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="URL">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z,a-z,0-9, ,_,\-,+,%]+.[a-z,A-Z]+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Choice">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="dynamic"/>
			<xs:enumeration value="static"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Ahmed-Refaat/yamcs/yamcs-web/src/main/uss/symlib/USS.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Libraries.xsd" name="USS">
  <comment />
  <symbol>
    <name>DynamicBox</name>
    <comment />
    <image default="false" state="green">U14_box_green.svg</image>
    <image default="false" state="red">U16_box_red.svg</image>
    <image default="false" state="yellow">U17_box_yellow.svg</image>
    <image default="true" state="grey">U15_box_grey.svg</image>
    <type>dynamic</type>
  </symbol>
  <symbol>
    <name>DynamicLed</name>
    <comment />
    <image default="false" state="green">U22_led_green.svg</image>
    <image default="false" state="red">U24_led_red.svg</image>
    <image default="false" state="yellow">U25_led_yellow.svg</image>
    <image default="true" state="grey">U23_led_grey.svg</image>
    <type>dynamic</type>
  </symbol>
  <symbol>
    <name>DynamicLed3D</name>
    <comment />
    <image default="false" state="green">U18_led_3D_green.svg</image>
    <image default="false" state="red">U20_led_3D_red.svg</image>
    <image default="false" state="yellow">U21_led_3D_yellow.svg</image>
    <image default="true" state="grey">U19_led_3D_grey.svg</image>
    <type>dynamic</type>
  </symbol>
  <symbol>
    <name>DynamicLine</name>
    <comment />
    <image default="true" state="nok">U26_line_nok.svg</image>
    <image default="false" state="ok">U28_line_ok.svg</image>
    <type>dynamic</type>
  </symbol>
  <symbol>
    <name>DynamicLineBig</name>
    <comment />
    <image default="true" state="nok">U27_line_nok_big.svg</image>
    <image default="false" state="ok">U29_line_ok_big.svg</image>
    <type>dynamic</type>
  </symbol>
  <symbol>
    <name>DynamicLink</name>
    <comment />
    <image default="true" state="up">U30_link_up.svg</image>
    <image default="false" state="undef">U32_link_undef.svg</image>
    <image default="false" state="down">U31_link_down.svg</image>
    <type>dynamic</type>
  </symbol>
  <symbol>
    <name>U1 Valve Three Way Motor L</name>
    <comment />
    <image>U1_Valve_Three_Way_Motor_L.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U10 Fan R</name>
    <comment />
    <image>U10_Fan_R.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U11 Video Monitor</name>
    <comment />
    <image>U11_Video_Monitor.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U12 Software</name>
    <comment />
    <image>U12_Software.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U13 Thermal Plate</name>
    <comment />
    <image>U13_Thermal_Plate.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U14 box green</name>
    <comment />
    <image>U14_box_green.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U15 box grey</name>
    <comment />
    <image>U15_box_grey.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U16 box red</name>
    <comment />
    <image>U16_box_red.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U17 box yellow</name>
    <comment />
    <image>U17_box_yellow.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U18 led 3D green</name>
    <comment />
    <image>U18_led_3D_green.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U19 led 3D grey</name>
    <comment />
    <image>U19_led_3D_grey.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U2 Valve Three Way Motor R</name>
    <comment />
    <image>U2_Valve_Three_Way_Motor_R.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U20 led 3D red</name>
    <comment />
    <image>U20_led_3D_red.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U21 led 3D yellow</name>
    <comment />
    <image>U21_led_3D_yellow.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U22 led green</name>
    <comment />
    <image>U22_led_green.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U23 led grey</name>
    <comment />
    <image>U23_led_grey.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U24 led red</name>
    <comment />
    <image>U24_led_red.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U25 led yellow</name>
    <comment />
    <image>U25_led_yellow.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U26 line nok</name>
    <comment />
    <image>U26_line_nok.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U27 line nok big</name>
    <comment />
    <image>U27_line_nok_big.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U28 line ok</name>
    <comment />
    <image>U28_line_ok.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U29 line ok big</name>
    <comment />
    <image>U29_line_ok_big.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U3 Valve Three Way Motor U</name>
    <comment />
    <image>U3_Valve_Three_Way_Motor_U.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U30 link up</name>
    <comment />
    <image>U30_link_up.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U31 link down</name>
    <comment />
    <image>U31_link_down.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U32 link undef</name>
    <comment />
    <image>U32_link_undef.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U4 Valve Two Way ManMot H</name>
    <comment />
    <image>U4_Valve_Two_Way_ManMot_H.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U5 Valve Two Way ManMot V</name>
    <comment />
    <image>U5_Valve_Two_Way_ManMot_V.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U6 Valve Two Way Motor H</name>
    <comment />
    <image>U6_Valve_Two_Way_Motor_H.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U7 Valve Two Way Motor V</name>
    <comment />
    <image>U7_Valve_Two_Way_Motor_V.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U8 Fan L</name>
    <comment />
    <image>U8_Fan_L.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>U9 Fan O</name>
    <comment />
    <image>U9_Fan_O.svg</image>
    <type>static</type>
  </symbol>
</library>

=== Ahmed-Refaat/yamcs/yamcs-web/src/main/uss/symlib/3D Graphics.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Libraries.xsd" name="3D Graphics">
  <comment />
  <symbol>
    <name>3D1 Camera Control Mode Fly Around</name>
    <comment />
    <image>3D1_Camera_Control_Mode_Fly_Around.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D1 Camera Rotate</name>
    <comment />
    <image>3D1_Camera_Rotate.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D1 Camera Translate</name>
    <comment />
    <image>3D1_Camera_Translate.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D10 Restore View</name>
    <comment />
    <image>3D10_Restore_View.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D11 Roll Left</name>
    <comment />
    <image>3D11_Roll_Left.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D11 Roll Left Alternate Pad</name>
    <comment />
    <image>3D11_Roll_Left_Alternate_Pad.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D11 Roll Right</name>
    <comment />
    <image>3D11_Roll_Right.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D11 Roll Right Alternate Pad</name>
    <comment />
    <image>3D11_Roll_Right_Alternate_Pad.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D12 Save View</name>
    <comment />
    <image>3D12_Save_View.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D13 Step Size</name>
    <comment />
    <image>3D13_Step_Size.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D14 Target</name>
    <comment />
    <image>3D14_Target.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D15 Translation Backward</name>
    <comment />
    <image>3D15_Translation_Backward.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D15 Translation Forward</name>
    <comment />
    <image>3D15_Translation_Forward.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D16 View Direction From The Moon</name>
    <comment />
    <image>3D16_View_Direction_From_The_Moon.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D16 View Direction From The Sun</name>
    <comment />
    <image>3D16_View_Direction_From_The_Sun.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D16 View Direction To The Earth</name>
    <comment />
    <image>3D16_View_Direction_To_The_Earth.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D17 Zoom</name>
    <comment />
    <image>3D17_Zoom.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D2 Camera Options</name>
    <comment />
    <image>3D2_Camera_Options.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D3 Default View</name>
    <comment />
    <image>3D3_Default_View.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D4 Display Options</name>
    <comment />
    <image>3D4_Display_Options.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D5 Earth Size 10xSmaller</name>
    <comment />
    <image>3D5_Earth_Size_10xSmaller.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D5 Earth Size Real Size</name>
    <comment />
    <image>3D5_Earth_Size_Real_Size.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D6 Motion Arrow</name>
    <comment />
    <image>3D6_Motion_Arrow.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D6 Motion Arrow Left Yaw Fly Around</name>
    <comment />
    <image>3D6_Motion_Arrow_Left_Yaw_Fly_Around.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D6 Motion Arrow Right Yaw Fly Around</name>
    <comment />
    <image>3D6_Motion_Arrow_Right_Yaw_Fly_Around.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D6 Motion Arrow Rotate Fly Around</name>
    <comment />
    <image>3D6_Motion_Arrow_Rotate_Fly_Around.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D6 Motion Arrow Translation</name>
    <comment />
    <image>3D6_Motion_Arrow_Translation.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D7 Panel Common</name>
    <comment />
    <image>3D7_Panel_Common.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D8 Pointers To The Moon</name>
    <comment />
    <image>3D8_Pointers_To_The_Moon.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D8 Pointers To The Sun</name>
    <comment />
    <image>3D8_Pointers_To_The_Sun.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D9 Reference Frame CCK</name>
    <comment />
    <image>3D9_Reference_Frame_CCK.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D9 Reference Frame ECK J2000</name>
    <comment />
    <image>3D9_Reference_Frame_ECK_J2000.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D9 Reference Frame LVLH</name>
    <comment />
    <image>3D9_Reference_Frame_LVLH.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D9 Reference Frame OCK</name>
    <comment />
    <image>3D9_Reference_Frame_OCK.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D9 Reference Frame PCO</name>
    <comment />
    <image>3D9_Reference_Frame_PCO.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D9 Reference Frame RS Body</name>
    <comment />
    <image>3D9_Reference_Frame_RS_Body.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D9 Reference Frame US Body</name>
    <comment />
    <image>3D9_Reference_Frame_US_Body.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>3D9 Reference Frame XPOP</name>
    <comment />
    <image>3D9_Reference_Frame_XPOP.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>P-3D1 Coordinate Platform</name>
    <comment />
    <image>P-3D1_Coordinate_Platform.gif</image>
    <type>static</type>
  </symbol>
</library>

=== Ahmed-Refaat/yamcs/yamcs-web/src/main/uss/symlib/General.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Libraries.xsd" name="General">
  <comment />
  <symbol>
    <name>G1 Additional Applications</name>
    <comment />
    <image>G1_Additional_Applications.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G10 Continue</name>
    <comment />
    <image>G10_Continue.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G11S Control Panel Generic</name>
    <comment />
    <image>G11S_Control_Panel_Generic.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G12S Control Zone Reference Information Forwarded</name>
    <comment />
    <image>G12S_Control_Zone_Reference_Information_Forwarded.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G13 Details</name>
    <comment />
    <image>G13_Details.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G14 Failure Status</name>
    <comment />
    <image>G14_Failure_Status.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G15S Fire Hole</name>
    <comment />
    <image>G15S_Fire_Hole.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G16 Freezer</name>
    <comment />
    <image>G16_Freezer.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G17S Galley Food Warmer</name>
    <comment />
    <image>G17S_Galley_Food_Warmer.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G18 Gauge</name>
    <comment />
    <image>G18_Gauge.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G19 Help</name>
    <comment />
    <image>G19_Help.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G2 Attention Symbol</name>
    <comment />
    <image>G2_Attention_Symbol.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G20 Information</name>
    <comment />
    <image>G20_Information.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G21 Log</name>
    <comment />
    <image>G21_Log.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G22 Meter Panel Analog</name>
    <comment />
    <image>G22_Meter_Panel_Analog.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G23 Mode</name>
    <comment />
    <image>G23_Mode.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G24 More Details</name>
    <comment />
    <image>G24_More_Details.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G25 Open</name>
    <comment />
    <image>G25_Open.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G26 Permission</name>
    <comment />
    <image>G26_Permission.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G27 Readiness</name>
    <comment />
    <image>G27_Readiness.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G28 Refrigerator</name>
    <comment />
    <image>G28_Refrigerator.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G28S Refrigerator</name>
    <comment />
    <image>G28S_Refrigerator.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G29S Remote Power Controller RPC</name>
    <comment />
    <image>G29S_Remote_Power_Controller_RPC.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G3 Bar Graph Horizontal</name>
    <comment />
    <image>G3_Bar_Graph_Horizontal.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G3 Bar Graph Vertical</name>
    <comment />
    <image>G3_Bar_Graph_Vertical.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G30S Remote Power Controller Mechanism RPCM</name>
    <comment />
    <image>G30S_Remote_Power_Controller_Mechanism_RPCM.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G32 Save</name>
    <comment />
    <image>G32_Save.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G33S Telemetry Diamond</name>
    <comment />
    <image>G33S_Telemetry_Diamond.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G34S Time Delay</name>
    <comment />
    <image>G34S_Time_Delay.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G35 Timer Animated</name>
    <comment />
    <image>G35_Timer_Animated.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G36 Timer External Process</name>
    <comment />
    <image>G36_Timer_External_Process.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G37 Timer Local Process</name>
    <comment />
    <image>G37_Timer_Local_Process.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G38S Voting</name>
    <comment />
    <image>G38S_Voting.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G40 Exit</name>
    <comment />
    <image>G40_Exit.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G4S Bubble Bit Bite</name>
    <comment />
    <image>G4S_Bubble_Bit_Bite.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G5S Bubble Command</name>
    <comment />
    <image>G5S_Bubble_Command.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G6S Bubble Telemetry</name>
    <comment />
    <image>G6S_Bubble_Telemetry.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G7S Bus Reference</name>
    <comment />
    <image>G7S_Bus_Reference.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G8 Center Point</name>
    <comment />
    <image>G8_Center_Point.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>G9S Command Time Out</name>
    <comment />
    <image>G9S_Command_Time_Out.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>P-G1 Cow Shed</name>
    <comment />
    <image>P-G1_Cow_Shed.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>P-G2 Menu</name>
    <comment />
    <image>P-G2_Menu.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>P-G3 No</name>
    <comment />
    <image>P-G3_No.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>P-G4 Resize Decrease</name>
    <comment />
    <image>P-G4_Resize_Decrease.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>P-G4 Resize Increase</name>
    <comment />
    <image>P-G4_Resize_Increase.gif</image>
    <type>static</type>
  </symbol>
</library>

=== Ahmed-Refaat/yamcs/yamcs-web/src/main/uss/symlib/Logic.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Libraries.xsd" name="Logic">
  <comment />
  <symbol>
    <name>L1S Gate AND</name>
    <comment />
    <image>L1S_Gate_AND.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>L2S Gate Exclusive OR</name>
    <comment />
    <image>L2S_Gate_Exclusive_OR.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>L3S Gate NAND</name>
    <comment />
    <image>L3S_Gate_NAND.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>L4S Gate NOR</name>
    <comment />
    <image>L4S_Gate_NOR.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>L5S Gate OR</name>
    <comment />
    <image>L5S_Gate_OR.gif</image>
    <type>static</type>
  </symbol>
</library>

=== Ahmed-Refaat/yamcs/yamcs-web/src/main/uss/symlib/Events.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Libraries.xsd" name="Events">
  <comment />
  <symbol>
    <name>EV1 Acquisition and Loss of Signal</name>
    <comment />
    <image>EV1_Acquisition_and_Loss_of_Signal.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>EV10 Switch English Russian</name>
    <comment />
    <image>EV10_Switch_English_Russian.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>EV10 Switch Russian English</name>
    <comment />
    <image>EV10_Switch_Russian_English.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>EV11 Light Shade Daylight Dark Trans Symbol Active Day</name>
    <comment />
    <image>EV11_Light_Shade_Daylight_Dark_Trans_Symbol_Active_Day.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>EV11 Light Shade Daylight Dark Trans Symbol Active Night</name>
    <comment />
    <image>EV11_Light_Shade_Daylight_Dark_Trans_Symbol_Active_Night.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>EV12 Navigation List</name>
    <comment />
    <image>EV12_Navigation_List.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>EV13 Navigation Tree</name>
    <comment />
    <image>EV13_Navigation_Tree.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>EV2 Advisory</name>
    <comment />
    <image>EV2_Advisory.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>EV3 Atmospheric Contamination</name>
    <comment />
    <image>EV3_Atmospheric_Contamination.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>EV4 Caution</name>
    <comment />
    <image>EV4_Caution.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>EV4 Warning</name>
    <comment />
    <image>EV4_Warning.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>EV5 Delta Pressure Delta Temperature (dPdT) Decompression</name>
    <comment />
    <image>EV5_Delta_Pressure_Delta_Temperature_%28dPdT%29_Decompression.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>EV6 Events Details</name>
    <comment />
    <image>EV6_Events_Details.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>EV7 Fire</name>
    <comment />
    <image>EV7_Fire.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>EV8 Home</name>
    <comment />
    <image>EV8_Home.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>EV9 Hot Key Mapping ESA</name>
    <comment />
    <image>EV9_Hot_Key_Mapping_ESA.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>EV9 Hot Key Mapping JAXA</name>
    <comment />
    <image>EV9_Hot_Key_Mapping_JAXA.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>EV9 Hot Key Mapping NASA</name>
    <comment />
    <image>EV9_Hot_Key_Mapping_NASA.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>EV9 Hot Key Mapping RASA</name>
    <comment />
    <image>EV9_Hot_Key_Mapping_RASA.gif</image>
    <type>static</type>
  </symbol>
</library>

=== Ahmed-Refaat/yamcs/yamcs-web/src/main/uss/symlib/Tasks.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Libraries.xsd" name="Tasks">
  <comment />
  <symbol>
    <name>T1 Attitude</name>
    <comment />
    <image>T1_Attitude.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>T2 Attitude Reboost</name>
    <comment />
    <image>T2_Attitude_Reboost.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>T3 Docking</name>
    <comment />
    <image>T3_Docking.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>T4 Liquid gas transfer C</name>
    <comment />
    <image>T4_Liquid_gas_transfer_C.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>T5 Undocking</name>
    <comment />
    <image>T5_Undocking.gif</image>
    <type>static</type>
  </symbol>
</library>
