=== Ahmed-Refaat/yamcs/yamcs-web/src/main/uss/symlib/Libraries.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="library">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="comment" type="xs:string"/>
				<xs:element ref="symbol" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="symbol">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string"/>
				<xs:element name="comment" type="xs:string"/>
				<xs:element ref="image" maxOccurs="unbounded"/>				
				<xs:element name="type" type="Choice"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="image">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="URL">
					<xs:attribute name="default">
						<xs:simpleType>
							<xs:restriction base="xs:NMTOKEN">
								<xs:enumeration value="false"/>
								<xs:enumeration value="true"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="state" type="xs:string"/>
					<xs:attribute name="library" type="xs:string"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="URL">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z,a-z,0-9, ,_,\-,+,%]+.[a-z,A-Z]+"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Choice">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="dynamic"/>
			<xs:enumeration value="static"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== Ahmed-Refaat/yamcs/yamcs-web/src/main/uss/symlib/Mechanical.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Libraries.xsd" name="Mechanical">
  <comment />
  <symbol>
    <name>M10S Gamah Fitting</name>
    <comment />
    <image>M10S_Gamah_Fitting.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M11 Grid</name>
    <comment />
    <image>M11_Grid.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M12 Grill</name>
    <comment />
    <image>M12_Grill.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M13 Guide Vanes A</name>
    <comment />
    <image>M13_Guide_Vanes_A.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M13 Guide Vanes B</name>
    <comment />
    <image>M13_Guide_Vanes_B.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M14 Hatch Edge On View A</name>
    <comment />
    <image>M14_Hatch_Edge_On_View_A.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M14 Hatch Edge On View B</name>
    <comment />
    <image>M14_Hatch_Edge_On_View_B.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M14S Hatch Edge On View C</name>
    <comment />
    <image>M14S_Hatch_Edge_On_View_C.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M14S Hatch Edge On View D</name>
    <comment />
    <image>M14S_Hatch_Edge_On_View_D.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M14S Hatch Edge on View A</name>
    <comment />
    <image>M14S_Hatch_Edge_on_View_A.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M14S Hatch Edge on View B</name>
    <comment />
    <image>M14S_Hatch_Edge_on_View_B.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M15 Hatch Front View</name>
    <comment />
    <image>M15_Hatch_Front_View.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M16 Lab Cradle Assembly</name>
    <comment />
    <image>M16_Lab_Cradle_Assembly.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M17S Panel Caution Warning</name>
    <comment />
    <image>M17S_Panel_Caution_Warning.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M18 Panel Close Out</name>
    <comment />
    <image>M18_Panel_Close_Out.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M19S Reflector</name>
    <comment />
    <image>M19S_Reflector.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M1S Actuator Electromechanical</name>
    <comment />
    <image>M1S_Actuator_Electromechanical.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M20S Spring Spiral</name>
    <comment />
    <image>M20S_Spring_Spiral.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M21S Spring Torsion</name>
    <comment />
    <image>M21S_Spring_Torsion.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M22 Torque Limiter Mechanical</name>
    <comment />
    <image>M22_Torque_Limiter_Mechanical.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M23 Umbilical Interface Assembly</name>
    <comment />
    <image>M23_Umbilical_Interface_Assembly.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M2S Bearing</name>
    <comment />
    <image>M2S_Bearing.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M3 Berthing Docking Target</name>
    <comment />
    <image>M3_Berthing_Docking_Target.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M4S Bevel Drive</name>
    <comment />
    <image>M4S_Bevel_Drive.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M5S Bulkhead Connector</name>
    <comment />
    <image>M5S_Bulkhead_Connector.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M6 Bulkhead Penetrator</name>
    <comment />
    <image>M6_Bulkhead_Penetrator.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M6S Bulkhead Penetrator</name>
    <comment />
    <image>M6S_Bulkhead_Penetrator.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M7 Capture Latch</name>
    <comment />
    <image>M7_Capture_Latch.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M8 Common Berthing Mechanism CBM</name>
    <comment />
    <image>M8_Common_Berthing_Mechanism_CBM.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>M9S Direct Drive Gear Train</name>
    <comment />
    <image>M9S_Direct_Drive_Gear_Train.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>P-M1 Spring</name>
    <comment />
    <image>P-M1_Spring.gif</image>
    <type>static</type>
  </symbol>
</library>

=== Ahmed-Refaat/yamcs/yamcs-web/src/main/uss/symlib/Sensors.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Libraries.xsd" name="Sensors">
  <comment />
  <symbol>
    <name>S1 Angular Rate Assembly</name>
    <comment />
    <image>S1_Angular_Rate_Assembly.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S10S Pressure Sensor Unit</name>
    <comment />
    <image>S10S_Pressure_Sensor_Unit.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S11 Pressure Sensor with Indicator</name>
    <comment />
    <image>S11_Pressure_Sensor_with_Indicator.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S12 Rate Gyro Assembly RGA</name>
    <comment />
    <image>S12_Rate_Gyro_Assembly_RGA.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S12S Rate Gyro Assembly RGA A</name>
    <comment />
    <image>S12S_Rate_Gyro_Assembly_RGA_A.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S12S Rate Gyro Assembly RGA B</name>
    <comment />
    <image>S12S_Rate_Gyro_Assembly_RGA_B.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S13 Satellite Navigation GLONASS</name>
    <comment />
    <image>S13_Satellite_Navigation_GLONASS.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S14 HumiditySensor</name>
    <comment />
    <image>S14_HumiditySensor.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S14 Sensor</name>
    <comment />
    <image>S14_Sensor.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S14 Sensor CO2</name>
    <comment />
    <image>S14_Sensor_CO2.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S14 Sensor Current</name>
    <comment />
    <image>S14_Sensor_Current.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S14 Sensor Current Delta</name>
    <comment />
    <image>S14_Sensor_Current_Delta.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S14 Sensor Delta Pressure</name>
    <comment />
    <image>S14_Sensor_Delta_Pressure.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S14 Sensor Dew Point</name>
    <comment />
    <image>S14_Sensor_Dew_Point.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S14 Sensor Flow Rate</name>
    <comment />
    <image>S14_Sensor_Flow_Rate.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S14 Sensor Generic</name>
    <comment />
    <image>S14_Sensor_Generic.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S14 Sensor Humidity</name>
    <comment />
    <image>S14_Sensor_Humidity.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S14 Sensor Liquid</name>
    <comment />
    <image>S14_Sensor_Liquid.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S14 Sensor Optical Smoke</name>
    <comment />
    <image>S14_Sensor_Optical_Smoke.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S14 Sensor Partial Pressure CO2</name>
    <comment />
    <image>S14_Sensor_Partial_Pressure_CO2.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S14 Sensor Partial Pressure Oxygen</name>
    <comment />
    <image>S14_Sensor_Partial_Pressure_Oxygen.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S14 Sensor Position</name>
    <comment />
    <image>S14_Sensor_Position.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S14 Sensor Pressure</name>
    <comment />
    <image>S14_Sensor_Pressure.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S14 Sensor Quantity</name>
    <comment />
    <image>S14_Sensor_Quantity.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S14 Sensor Rate</name>
    <comment />
    <image>S14_Sensor_Rate.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S14 Sensor Tachometer</name>
    <comment />
    <image>S14_Sensor_Tachometer.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S14 Sensor Temperature</name>
    <comment />
    <image>S14_Sensor_Temperature.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S14 Sensor Voltage</name>
    <comment />
    <image>S14_Sensor_Voltage.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S14 Sensor Volume</name>
    <comment />
    <image>S14_Sensor_Volume.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S15 Smoke Detector</name>
    <comment />
    <image>S15_Smoke_Detector.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S16 Star Mapper</name>
    <comment />
    <image>S16_Star_Mapper.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S17 Star Sensor</name>
    <comment />
    <image>S17_Star_Sensor.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S18 Strain Gauge Assembly</name>
    <comment />
    <image>S18_Strain_Gauge_Assembly.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S19S Sun Sensor</name>
    <comment />
    <image>S19S_Sun_Sensor.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S1S Angular Rate Assembly</name>
    <comment />
    <image>S1S_Angular_Rate_Assembly.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S2 Angular Rate Processed Output Assembly</name>
    <comment />
    <image>S2_Angular_Rate_Processed_Output_Assembly.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S20S Sun Sensor Fixed Head</name>
    <comment />
    <image>S20S_Sun_Sensor_Fixed_Head.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S21 Sun Sensor Scanning</name>
    <comment />
    <image>S21_Sun_Sensor_Scanning.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S21S Sun Sensor Scanning</name>
    <comment />
    <image>S21S_Sun_Sensor_Scanning.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S22 Thermostat</name>
    <comment />
    <image>S22_Thermostat.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S2S Angular Rate Processed Output Assembly</name>
    <comment />
    <image>S2S_Angular_Rate_Processed_Output_Assembly.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S3 Control Moment Gyro CMG</name>
    <comment />
    <image>S3_Control_Moment_Gyro_CMG.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S4 Electric Conductivity Sensor</name>
    <comment />
    <image>S4_Electric_Conductivity_Sensor.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S5 Flow Indicator</name>
    <comment />
    <image>S5_Flow_Indicator.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S6 Gyrodyne</name>
    <comment />
    <image>S6_Gyrodyne.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S7 Infared Horizon Sensor</name>
    <comment />
    <image>S7_Infared_Horizon_Sensor.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S8 Magnetometer</name>
    <comment />
    <image>S8_Magnetometer.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>S9 Pressure Differential Sensor</name>
    <comment />
    <image>S9_Pressure_Differential_Sensor.gif</image>
    <type>static</type>
  </symbol>
</library>

=== Ahmed-Refaat/yamcs/yamcs-web/src/main/uss/symlib/Station Modules.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Libraries.xsd" name="Station Modules">
  <comment />
  <symbol>
    <name>SS1 Airlock</name>
    <comment />
    <image>SS1_Airlock.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>SS10 Multi Purpose Logisticss Module MPLM</name>
    <comment />
    <image>SS10_Multi_Purpose_Logisticss_Module_MPLM.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>SS11 Node NASA A</name>
    <comment />
    <image>SS11_Node_NASA_A.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>SS11 Node NASA B</name>
    <comment />
    <image>SS11_Node_NASA_B.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>SS11 Node RASA</name>
    <comment />
    <image>SS11_Node_RASA.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>SS12 Pressurized Mating Adapter PMA</name>
    <comment />
    <image>SS12_Pressurized_Mating_Adapter_PMA.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>SS13 Progress</name>
    <comment />
    <image>SS13_Progress.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>SS14 Service Module SM Zvezda NASA</name>
    <comment />
    <image>SS14_Service_Module_SM_Zvezda_NASA.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>SS14 Service Module SM Zvezda RASA</name>
    <comment />
    <image>SS14_Service_Module_SM_Zvezda_RASA.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>SS15 Soyuz Transfer Vehicle RASA</name>
    <comment />
    <image>SS15_Soyuz_Transfer_Vehicle_RASA.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>SS16 Truss Segment NASA</name>
    <comment />
    <image>SS16_Truss_Segment_NASA.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>SS16 Truss Segment RASA</name>
    <comment />
    <image>SS16_Truss_Segment_RASA.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>SS17 Truss Segment with Solar Array</name>
    <comment />
    <image>SS17_Truss_Segment_with_Solar_Array.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>SS18 US Lab US Destiny NASA</name>
    <comment />
    <image>SS18_US_Lab_US_Destiny_NASA.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>SS2 Automated Transfer Vehicle ATV NASA</name>
    <comment />
    <image>SS2_Automated_Transfer_Vehicle_ATV_NASA.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>SS2 Automated Transfer Vehicle ATV RASA</name>
    <comment />
    <image>SS2_Automated_Transfer_Vehicle_ATV_RASA.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>SS3 Columbus</name>
    <comment />
    <image>SS3_Columbus.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>SS4 Docking Compartment NASA</name>
    <comment />
    <image>SS4_Docking_Compartment_NASA.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>SS4 Docking Compartment RASA</name>
    <comment />
    <image>SS4_Docking_Compartment_RASA.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>SS5 Functional Cargo Block FGB Zarya Control Module NASA</name>
    <comment />
    <image>SS5_Functional_Cargo_Block_FGB_Zarya_Control_Module_NASA.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>SS5 Functional Cargo Block FGB Zarya Control Module RASA</name>
    <comment />
    <image>SS5_Functional_Cargo_Block_FGB_Zarya_Control_Module_RASA.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>SS6 HII Transfer Vehicle HTV</name>
    <comment />
    <image>SS6_HII_Transfer_Vehicle_HTV.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>SS7 Japan Experiment Logistics Module JEF</name>
    <comment />
    <image>SS7_Japan_Experiment_Logistics_Module_JEF.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>SS8 Japan Experiment Logisitcs Module JLP</name>
    <comment />
    <image>SS8_Japan_Experiment_Logisitcs_Module_JLP.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>SS9 Japan Pressurized Module JPM</name>
    <comment />
    <image>SS9_Japan_Pressurized_Module_JPM.svg</image>
    <type>static</type>
  </symbol>
</library>

=== Ahmed-Refaat/yamcs/yamcs-web/src/main/uss/symlib/Groups.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Libraries.xsd" name="Groups">
  <comment />
  <symbol>
    <name>GR1 Command and Data Group</name>
    <comment />
    <image>GR1_Command_and_Data_Group.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>GR1 Command and Data Handling</name>
    <comment />
    <image>GR1_Command_and_Data_Handling.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>GR10 Integrated Operations</name>
    <comment />
    <image>GR10_Integrated_Operations.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>GR11 Payloads Group</name>
    <comment />
    <image>GR11_Payloads_Group.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>GR12 Robotics Group</name>
    <comment />
    <image>GR12_Robotics_Group.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>GR12-a Europeon Robotic Arm ERA</name>
    <comment />
    <image>GR12-a_Europeon_Robotic_Arm_ERA.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>GR13 Transfer Vehicle Group</name>
    <comment />
    <image>GR13_Transfer_Vehicle_Group.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>GR13-a Kurs Radar Docking System</name>
    <comment />
    <image>GR13-a_Kurs_Radar_Docking_System.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>GR2 Communication and Tracking Group</name>
    <comment />
    <image>GR2_Communication_and_Tracking_Group.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>GR2-a Flight Data Telemetry System</name>
    <comment />
    <image>GR2-a_Flight_Data_Telemetry_System.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>GR2-b SM Comm System</name>
    <comment />
    <image>GR2-b_SM_Comm_System.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>GR2-c Television System</name>
    <comment />
    <image>GR2-c_Television_System.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>GR3 Electrical Power Group</name>
    <comment />
    <image>GR3_Electrical_Power_Group.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>GR4 Environmental Control Group</name>
    <comment />
    <image>GR4_Environmental_Control_Group.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>GR5 Motion Control Group</name>
    <comment />
    <image>GR5_Motion_Control_Group.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>GR5-a Navigation</name>
    <comment />
    <image>GR5-a_Navigation.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>GR5-b Thrust Assist</name>
    <comment />
    <image>GR5-b_Thrust_Assist.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>GR5-c SM Integrated Propulsion System</name>
    <comment />
    <image>GR5-c_SM_Integrated_Propulsion_System.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>GR6 Structures and Mechanisms Group</name>
    <comment />
    <image>GR6_Structures_and_Mechanisms_Group.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>GR6-a Docking and Internal Transfer System</name>
    <comment />
    <image>GR6-a_Docking_and_Internal_Transfer_System.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>GR7 Thermal Control Group</name>
    <comment />
    <image>GR7_Thermal_Control_Group.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>GR8 Extravehicular Activity Group</name>
    <comment />
    <image>GR8_Extravehicular_Activity_Group.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>GR9 Integrated Medical Group</name>
    <comment />
    <image>GR9_Integrated_Medical_Group.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>GR9-a Radiation Monitoring System</name>
    <comment />
    <image>GR9-a_Radiation_Monitoring_System.gif</image>
    <type>static</type>
  </symbol>
</library>

=== Ahmed-Refaat/yamcs/yamcs-web/src/main/uss/symlib/Radiation Monitoring.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Libraries.xsd" name="Radiation Monitoring">
  <comment />
  <symbol>
    <name>RM1 Dosimeter</name>
    <comment />
    <image>RM1_Dosimeter.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>RM2 Individual Dose</name>
    <comment />
    <image>RM2_Individual_Dose.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>RM3 Radiation Monitoring Subsystem</name>
    <comment />
    <image>RM3_Radiation_Monitoring_Subsystem.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>RM4 Radiometer</name>
    <comment />
    <image>RM4_Radiometer.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>RM5 Solar Flare</name>
    <comment />
    <image>RM5_Solar_Flare.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>RM6 Workplace</name>
    <comment />
    <image>RM6_Workplace.gif</image>
    <type>static</type>
  </symbol>
</library>

=== Ahmed-Refaat/yamcs/yamcs-web/src/main/uss/symlib/Modes.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Libraries.xsd" name="Modes">
  <comment />
  <symbol>
    <name>MO1 Crew Rescue Mode</name>
    <comment />
    <image>MO1_Crew_Rescue_Mode.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>MO10 Survival Mode</name>
    <comment />
    <image>MO10_Survival_Mode.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>MO2 Extravehicular Activity EVA</name>
    <comment />
    <image>MO2_Extravehicular_Activity_EVA.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>MO2 Extravehicular Activtiy EVA</name>
    <comment />
    <image>MO2_Extravehicular_Activtiy_EVA.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>MO3 Gyrodyne Spin Up</name>
    <comment />
    <image>MO3_Gyrodyne_Spin_Up.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>MO4 Initial Attitude</name>
    <comment />
    <image>MO4_Initial_Attitude.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>MO5 Microgravity</name>
    <comment />
    <image>MO5_Microgravity.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>MO6 Proximity Operations Docking Target</name>
    <comment />
    <image>MO6_Proximity_Operations_Docking_Target.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>MO7 Reboost</name>
    <comment />
    <image>MO7_Reboost.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>MO8 Refuel</name>
    <comment />
    <image>MO8_Refuel.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>MO9 Standard Nominal</name>
    <comment />
    <image>MO9_Standard_Nominal.svg</image>
    <type>static</type>
  </symbol>
</library>

=== Ahmed-Refaat/yamcs/yamcs-web/src/main/uss/symlib/Computers.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Libraries.xsd" name="Computers">
  <comment />
  <symbol>
    <name>K1 Bus Coupler</name>
    <comment />
    <image>K1_Bus_Coupler.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>K10S Mouse Pointing Device</name>
    <comment />
    <image>K10S_Mouse_Pointing_Device.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>K11 MDM 1 Channel</name>
    <comment />
    <image>K11_MDM_1_Channel.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>K12 MDM 3 Channel</name>
    <comment />
    <image>K12_MDM_3_Channel.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>K13 Network Channel Controller</name>
    <comment />
    <image>K13_Network_Channel_Controller.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>K13S Network Channel Controller</name>
    <comment />
    <image>K13S_Network_Channel_Controller.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>K14S Output</name>
    <comment />
    <image>K14S_Output.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>K15 Sampling Unit</name>
    <comment />
    <image>K15_Sampling_Unit.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>K16 Switch Automated Payload</name>
    <comment />
    <image>K16_Switch_Automated_Payload.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>K17 Switching Unit</name>
    <comment />
    <image>K17_Switching_Unit.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>K18 Terminal Switching Unit</name>
    <comment />
    <image>K18_Terminal_Switching_Unit.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>K2S Channel Selector with Logic Control</name>
    <comment />
    <image>K2S_Channel_Selector_with_Logic_Control.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>K3 Computer Laptop</name>
    <comment />
    <image>K3_Computer_Laptop.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>K4 Computer One Channel</name>
    <comment />
    <image>K4_Computer_One_Channel.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>K5 Computer Three Channel</name>
    <comment />
    <image>K5_Computer_Three_Channel.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>K6 Discrete Input Output Device</name>
    <comment />
    <image>K6_Discrete_Input_Output_Device.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>K6 Discrete Input Output Signal</name>
    <comment />
    <image>K6_Discrete_Input_Output_Signal.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>K7S Input</name>
    <comment />
    <image>K7S_Input.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>K8S Keyboard</name>
    <comment />
    <image>K8S_Keyboard.gif</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>K9 Monitor</name>
    <comment />
    <image>K9_Monitor.svg</image>
    <type>static</type>
  </symbol>
  <symbol>
    <name>P-K1 Terminator</name>
    <comment />
    <image>P-K1_Terminator.gif</image>
    <type>static</type>
  </symbol>
</library>
